### ISSUE TITLE
Bees + Dynamic Trees Compatibility

### ISSUE THREAD

**Issue by CalaMariGold** [thedarkcolour/Future-MC#86] opened 2019-12-28 19:55 UTC
Bee hives don't spawn when Dynamic Trees are present. It would be amazing if we could get compatibility for this!

Thank you!

**Comment by lizelive** [comment] 2019-12-31 18:19
bees would bee the bees knees

**Comment by thedarkcolour** [comment] 2020-01-07 15:54
I'll see what Dynamic Trees does and if I can hook into it.

**Comment by SandwichHorror** [comment] 2020-03-06 19:31
This compatibility would make a world of difference. Looking forward to this!

**Comment by Serifina** [comment] 2020-03-15 02:26
I would also greatly appreciate this particular compatability!

**Comment by CalaMariGold** [comment] 2020-04-05 03:32
Any updates on this?

**Comment by thedarkcolour** [comment] 2020-04-06 19:41
I've gotten it to work partially.

**Comment by harrislapiroff** [comment] 2020-08-19 22:10
Another person excited for bees/dynamic trees compat! Thanks for your work! <3

**Comment by juliantcf** [comment] 2020-09-11 23:35
You mentioned on Discord getting bee nests to spawn, though they glitched out as the tree grew. Assuming you haven't scrapped the code, would you consider adding this as an experimental feature in config, disabled by default? Floating nests are better than no nests. If not, perhaps I could take a crack at it.

**Comment by APlayGames** [comment] 2021-03-14 17:31
It's been half a year since last message, @thedarkcolour are you ever going to work on this or no

**Comment by thedarkcolour** [comment] 2021-03-14 18:28
I forgot to reply here. I tried it at one point and it did not work as intended but I think I could try again

**Comment by democat3457** [comment] 2021-03-14 21:08
(btw @APlayGames it ended up putting hives on every single dynamic tree 😆)

**Comment by harrislapiroff** [comment] 2021-03-18 19:55
I would still be excited about this if you have the time @thedarkcolour :)

**Comment by Macleykun** [comment] 2021-06-09 20:35
This is also gonna be fixed with the support of this https://github.com/thedarkcolour/Future-MC/issues/234

**Comment by Serifina** [comment] 2021-06-23 05:48
Any idea when an update with that might happen?

**Comment by Druwan-ctrl** [comment] 2021-06-29 07:55
It would be awesome if you could get the time to look into it! Other bees implementations are... lacking

**Comment by Macleykun** [comment] 2021-09-26 18:30
Hey @mooofins have you been able to look at this issue with OTG and FMC/Bees?

**Comment by mooofins** [comment] 2021-09-26 20:40
No, sorry. My last and final update on the other bug was where I left off.

**Comment by Macleykun** [comment] 2021-10-03 20:29
Small update on this issue, i talked with mooofins and he won't work on this issue: I don’t really want to look into the bees one tbh; too open ended.
Tottaly understandable and i do want to thank him for his time and effort! 

I talked to the dev and he had some work put into it, but hasn't been able to get around of this just yet!

**Comment by Macleykun** [comment] 2021-11-06 14:39
I talked with Smileycorp and he said the following to solve this issue:

> for dynamic trees compatability you could hook into the SpeciesPostGenerationEvent to figure out when a tree is being generated and from there figure out if to and generate a beehive at the tree's location

for most modded trees you should be able to detect their generation using the DecorateBiomeEvent.Decorate, unless they do weird things with their trees, using the EventType.TREE, and add beehives using that, i'd probably suggest running it at EventPriority.LOWEST and set recieveCancelled to true so you can generate the hives after other mods replace generated trees with their own

i'm sorry i don't rally have much time at the moment to actually add the fix and also the mod is written in kotlin which i don't really know, but I think the principles should work for futuremc


Perhaps this can help clarify the issue more, so We can find a solution!

here is some stuff I prepared so anyone can easily setup the test environment!
https://cdn.discordapp.com/attachments/864829008134668318/901182038823010344/allbiomesinfmcformat.txt (A valid confix that makes almost every compatible tree have a beehive)

 Seed: -1223960747440536249

Modpack https://cdn.discordapp.com/attachments/864829008134668318/901179544747270165/OTGFMC.zip

![953AA834-D937-4594-BDFA-2B3005D3341A](https://user-images.githubusercontent.com/26381427/140613495-bcdf15ee-246b-409c-9e37-bb13c1e0d8db.png)
![5E979C6A-34C0-483F-B053-EFD1A4FF4FD8](https://user-images.githubusercontent.com/26381427/140613500-0856cd90-85b3-4cfe-9ec0-dd48b0fd22ac.png)
![E8615929-560C-4BC8-B577-EE0C00573034](https://user-images.githubusercontent.com/26381427/140613502-14921e05-258c-4816-94d8-3dccffb0d1e8.png)

**Comment by Macleykun** [comment] 2021-11-09 21:05
I'm willing to pay anyone who is able to fix the bees part 20 euro's.
10 upfront if shown/discussed and when a pull/jar is provided, the final 10.
Will do with paypal if that's ok.
Offer will stand no matter how long it takes.

**Comment by Macleykun** [comment] 2021-11-23 22:43
![3E0148DB-84C4-4490-892E-999FB1F49D6C](https://user-images.githubusercontent.com/26381427/143140559-b1ff2c09-ea08-4078-be10-7afdc154efc8.png)
![041E6C4D-0BF6-453F-B30B-A6231949617D](https://user-images.githubusercontent.com/26381427/143140565-52af66ea-f0d4-4f01-b7ef-c6c4c5948f43.png)

we’re getting close with the bees!!! Thanks to thedarkcolour!

**Comment by Macleykun** [comment] 2021-11-27 12:23
It seems the change is on public repo to include bees everywhere! But it seems that the mod doesn't compile anymore due to:
https://pastebin.com/0WXHEEf2

As soon as thedarkcolour pushes a fix, the jar actually will be there in the summary tab of that commit!
I've tried the previous commits, but it seems the bug came from the change itself sadly.
I'll throw the (preview) jar here once that's out :-)

**Comment by Macleykun** [comment] 2021-11-27 22:37
[FutureMC (2).zip](https://github.com/thedarkcolour/Future-MC/files/7612463/FutureMC.2.zip)

here’s the working preview of FMC where bees can spawn in OTG!

it’ll eventually be released officially after some more bug are fixed :)

ill unsub from this thread as it’s only for dynamic trees which I’m not interested in.

take care everyone!

**Comment by Macleykun** [comment] 2021-12-03 23:01
Seems to be a bug which crashes the game, reported and hopefully it’ll be fixed soon!

**Comment by Macleykun** [comment] 2021-12-28 11:24
Latest update support Biome Bundle!
Did ask if it’s also possible to do Biome Bundle o Plenty!

**Comment by Serifina** [comment] 2021-12-28 11:28
It's great it works with Biome Bundle. But... uh..

This issue was specifically about supporting Dynamic Trees. Is that or is that not happening?

**Comment by Macleykun** [comment] 2021-12-28 11:29
Not sure, ya can try 
This issue is also about bees :p I’m in for the bees haha

**Comment by Macleykun** [comment] 2021-12-30 09:12
![1unknown](https://user-images.githubusercontent.com/26381427/147737875-33d0c148-6712-4eeb-824c-10f271b714c5.png)
![unknown](https://user-images.githubusercontent.com/26381427/147737877-80acc91f-82f7-4131-bf3a-1827fea60ad2.png)
biomes o plenty is a work in progress because some of the trees are irregular -tdc

**Comment by Macleykun** [comment] 2022-01-27 21:33
I'm moving on from minecraft, i won't be keeping an eye progress on the bee part.

**Closed** 2022-03-28 06:45 UTC
Labels: enhancement, upcoming fix, compatibility
