### ISSUE TITLE
Crash entity

### ISSUE THREAD

**Issue by HeberonYT** [thedarkcolour/Future-MC#135] opened 2020-05-07 21:32 UTC
I am receiving these reports unexpectedly, they even occur while afk.
version: future-mc-1.12.2-0.2.02
Forge 2847
https://pastebin.com/raw/8NakbYFz

**Comment by thedarkcolour** [comment] 2020-05-08 07:00
Duplicate of #115

**Closed by thedarkcolour** 2020-05-08 07:00 UTC
