### ISSUE TITLE
Grindstone bug

### ISSUE THREAD

**Issue by AlterDimension** [thedarkcolour/Future-MC#136] opened 2020-05-08 19:37 UTC
If you right click the grindstone with say, a stone block/any other block, it would give the place animation but would not actually place the block which is a good thing. However, once you use waterbucket, it would place the water that does not disappear until you esc out of the grindstone menu and pick the water back up. I had to place torches on top and in front of hte grindstone to prevent this issue from happening. Please look into this :)

**Comment by thedarkcolour** [comment] 2020-05-08 21:38
I think that this is a duplicate of #121 (which I've already found a fix for) but I'll double check before closing this issue.

**Comment by thedarkcolour** [comment] 2020-05-08 21:38
Yup we're good here.

**Closed by thedarkcolour** 2020-05-08 21:38 UTC
