### ISSUE TITLE
Netherite crash

### ISSUE THREAD

**Issue by SpGilbert** [thedarkcolour/Future-MC#120] opened 2020-04-17 22:17 UTC
In the 1.15.2 version summoning, netherite crashes the game
Crash report:
https://paste.dimdev.org/oqidiliyab.rb
Latest log:
https://paste.dimdev.org/otifufusim.md

**Comment by SpGilbert** [comment] 2020-04-17 22:59
Crash report: (for when I tried to relog the world)
https://paste.dimdev.org/mecinukumo.mccrash
Latest log:
https://paste.dimdev.org/padotuxera.md
 (I also thought it was worth mentioning for the main post I had to press close program. while in this case, it crashed on its own.

**Comment by thedarkcolour** [comment] 2020-04-18 03:39
You mean summoning the item? Or using /give?

**Comment by SpGilbert** [comment] 2020-04-18 04:08
/give and when it is in your inventory

**Comment by thedarkcolour** [comment] 2020-04-19 05:18
I can't reproduce this. Can you try with just Future MC and Kotlin for Forge?

**Comment by Zidiath** [comment] 2020-04-22 09:57
any chance you are using Performant? I was having a similar crash and found that was causing the issue.

**Comment by SpGilbert** [comment] 2020-04-22 13:18
I think it may have to fo with other mods and yes I'm using perormant.

**Comment by thedarkcolour** [comment] 2020-04-23 23:17
I'm gonna close this as a more specific one just got created. #125

**Closed by thedarkcolour** 2020-04-23 23:17 UTC
Labels: bug, can't reproduce
