### ISSUE TITLE
Stripped log bug

### ISSUE THREAD

**Issue by Kuwagumo** [thedarkcolour/Future-MC#368] opened 2024-07-20 11:23 UTC
It seems that after one of the updates, the stripped logs entries were removed, but it's still possible to right click logs with an axe in order to strip them, leaving a no texture block with no properties, as if it was air. It crashes too soon after.

**Comment by thedarkcolour** [comment] 2024-07-30 01:29
Are you using Oceanic Expanse?

**Comment by thedarkcolour** [comment] 2024-07-30 02:35
Duplicate of #359

**Closed by thedarkcolour** 2024-07-30 02:35 UTC
Labels: bug, upcoming fix

**Comment by Kuwagumo** [comment] 2024-08-01 19:17
> Are you using Oceanic Expanse?

yes! that's what i discovered. Fixed it by disabling the compat. Sorry for the bother!

**Comment by thedarkcolour** [comment] 2024-08-01 19:18
Don't worry. It will be fixed next update.
