### ISSUE TITLE
Future MC crash with Minor Integrations and Additions (MIA)

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [thedarkcolour/Future-MC#272] opened 2021-10-31 15:27 UTC
I have the latest version of Forge and both of these mods. I checked the GitHub for Minor Integrations and Additions (MIA) and there was an issue exactly like the one I'm having. I'm only posting this here to make sure that this bug is known.

Here is the crash report: (https://pastebin.com/Q4uCGV3i)

Here is the latest log: (https://pastebin.com/AmLERhNQ)

**Comment by thedarkcolour** [comment] 2021-10-31 15:54
MIA hasn't been updated yet to work with newest version of FutureMC.

**Comment by thedarkcolour** [comment] 2021-10-31 18:05
I just tried it, can't reproduce.

**Comment by thedarkcolour** [comment] 2021-10-31 18:13
Try with Future MC 0.2.7.4

**Comment by 23KiaraMinecraft** [comment] 2021-11-01 01:07
I did and this is what I got. It still crashed.

Crash Report: (https://pastebin.com/3hYW1zWq)

Latest Log: (https://paste.ee/p/qMuBG)

**Comment by thedarkcolour** [comment] 2021-11-01 01:43
Ya looks like they still have to update MIA to work with new fmc

**Comment by SokyranTheDragon** [comment] 2021-11-09 23:28
Hey, MIA dev here. I haven't noticed an issue on my mod's Github page due to misconfigured notification settings, so I only realized yesterday that there's some issues.

From what I saw, the issue is that I reference Netherite armor in a few places (for example, when Thermal Expansion is present I add recipes to recycle it in similar ways it's done with other armor by that mod), and the `FireproofArmorItem` class was renamed to `NetheriteArmorItem`. The simple fix would have been to recompile my mod with the most recent FutureMC version present. I suppose this is a downside of how I handle my mod, by directly referencing other stuff in other mods (and considering the amount of mods I work with, it's more convenient for me).

I've noticed you attempted to fix it on your side (I assume that this attempt was the `@JvmField` annotations for a couple of fields). Feel free to revert it, as it won't really have any effect on my mod. The only thing it changes is that to reference specific blocks, I need to call `FBlocks.LILY_OF_THE_VALLEY` as opposed of `FBlocks.INSTANCE.getLILY_OF_THE_VALLEY()`, as it is right now. This is not a big deal on my end.

Anyway, I should update my mod (hopefully) tomorrow with a fix for this.

**Comment by thedarkcolour** [comment] 2021-11-09 23:55
I brought back the old fireproof armor class because I changed other things besides renaming the class (knockback resistance)
If you need anything else to make the armor class easier to use, let me know

**Comment by SokyranTheDragon** [comment] 2021-11-10 17:41
Oh, thanks for helping out, but you didn't have to. As I said in my previous message, I just needed to compile my project again to fix the issues. You don't really have to worry about me that much, as it's at most a couple smaller changes on my part.

**Comment by SokyranTheDragon** [comment] 2021-11-16 00:48
I've uploaded a new version of my mod, which should fix this issue. It's currently "Under Review", so it might take a little bit before it's official up on Curseforge.

**Closed** 2021-11-19 05:53 UTC
Labels: bug, can't reproduce, compatibility
