### ISSUE TITLE
[1.12.2] Seagrass appears in config file despite not being implemented

### ISSUE THREAD

**Issue by disastercube** [thedarkcolour/Future-MC#195] opened 2020-09-19 18:15 UTC
**VERSION:** Future MC **1.12.2** 0.2.4.1

**FISH**
----------------------------
Every fish mob has an incorrect forward movement. Instead of facing the direction of its path, it looks more like it is sliding from the side, making it looks really funky and unrealistic.

**SEAGRASS**
----------------------------
By default, seagrass is disabled in the config file, but even by turning it on it still doesn't spawn or do anything .

**Comment by thedarkcolour** [comment] 2020-09-26 23:57
Fish is a duplicate of #134 
Seagrass is a typo

**Closed** 2021-02-01 19:13 UTC
Labels: bug, upcoming fix
