### ISSUE TITLE
[1.12.2] Crashing during runtime deobfuscation

### ISSUE THREAD

**Issue by ChesterS1** [thedarkcolour/Future-MC#160] opened 2020-06-17 22:33 UTC
The mod keeps crashing me for no reason and it's not leaving a crash report either. Please help!

**Comment by thedarkcolour** [comment] 2020-06-20 03:12
Install forgelin

**Comment by Alee-OneHit** [comment] 2020-06-21 19:16
use SecurityCraft v1.8.18.2 ?

**Comment by thedarkcolour** [comment] 2020-07-10 21:39
Can't reproduce

**Comment by thedarkcolour** [comment] 2020-09-07 20:01
If you can't give me info/crash log I'm going to close the issue

**Closed** 2020-09-14 06:26 UTC
Labels: can't reproduce, need info
